{
  config,
  lib,
  pkgs,
  osConfig ? { },
  ...
}:
let
  # Check if AI module is enabled at system level
  aiEnabled = osConfig.services.ai.enable or false;

  # Template for user's init.lua
  initLuaTemplate = ''
    -- axiOS Neovim Configuration
    -- This file is user-owned - customize freely!
    -- Generated by axiOS, but you can modify it.

    -- Leader key (MUST be set before loading plugins)
    vim.g.mapleader = " "
    vim.g.maplocalleader = " "

    -- Load axios preset with your customizations
    require("axios").setup({
      -- Uncomment and modify to customize:

      -- colorscheme = "tokyonight",  -- Change colorscheme

      -- plugins = {
      --   disabled = { "neo-tree.nvim" },  -- Disable specific plugins
      -- },

      -- lsp = {
      --   servers = {
      --     nil_ls = {  -- Override LSP settings
      --       settings = { ["nil"] = { formatting = { command = { "nixfmt" } } } },
      --     },
      --   },
      -- },

      -- ai = {
      --   provider = "claude",
      --   claude = {
      --     auth_type = "api",  -- "api", "pro", or "max"
      --   },
      -- },
    })

    -- Add your custom configuration below:
    -- vim.opt.colorcolumn = "80"
    -- vim.keymap.set("n", "<leader>h", ":echo 'Hello!'<CR>")
  '';
in
{
  # Enable neovim via home-manager
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    vimdiffAlias = true;

    # Dependencies that should always be available
    extraPackages = with pkgs; [
      # LSPs (always available)
      nil # Nix
      lua-language-server

      # Formatters
      nixfmt-rfc-style
      stylua

      # Tools needed by plugins
      ripgrep
      fd
      lazygit
      tree-sitter

      # Build tools for plugins
      gcc
      gnumake
    ];

    # Add the axios preset to neovim's runtime path
    extraLuaConfig = ''
      -- Add axios preset to runtime path
      vim.opt.rtp:prepend("${pkgs.axios-nvim-preset}")
    '';
  };

  # Set environment variables for the preset
  home.sessionVariables = lib.mkMerge [
    # AI enabled flag
    (lib.mkIf aiEnabled {
      AXIOS_AI_ENABLED = "1";
    })
  ];

  # Bootstrap init.lua if it doesn't exist
  home.activation.neovimAxiosBootstrap = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        NVIM_CONFIG_DIR="${config.home.homeDirectory}/.config/nvim"
        INIT_LUA="$NVIM_CONFIG_DIR/init.lua"

        if [ ! -f "$INIT_LUA" ]; then
          run mkdir -p "$NVIM_CONFIG_DIR"
          run cat > "$INIT_LUA" << 'AXIOSEOF'
    ${initLuaTemplate}
    AXIOSEOF
          verbose "Created neovim config with axios IDE preset"
        fi
  '';
}
