{
  pkgs,
  lib,
  config,
  ...
}:
{
  programs.ghostty = {
    enable = true;
    package = pkgs.ghostty;
    enableFishIntegration = true;
    installVimSyntax = true;
  };

  # Override systemd service to keep ghostty resident for drop-down terminal
  # Default service exits when all windows close, breaking Mod+` drop-down
  systemd.user.services."app-com.mitchellh.ghostty" = {
    Service = {
      ExecStart = lib.mkForce "${pkgs.ghostty}/bin/ghostty --gtk-single-instance=true --initial-window=false --quit-after-last-window-closed=false";
    };
  };

  # Generate ghostty config directly via xdg.configFile
  # Note: dankcolors are loaded separately via config-file directive
  # Note: Drop-down terminal is handled by Niri keybind (Mod+grave) in niri.nix,
  #       not by Ghostty's global keybind (Wayland doesn't support app-level global keybinds)
  xdg.configFile."ghostty/config".text = ''
    # Ghostty Configuration

    # Import dankcolors theme (if it exists)
    # This file is generated by DankMaterialShell (matugen)
    config-file = ${config.home.homeDirectory}/.config/ghostty/themes/dankcolors
  '';

  # Ensure the theme directory and placeholder exist to prevent errors on first run
  home.activation.createGhosttyThemeDir = config.lib.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p ${config.home.homeDirectory}/.config/ghostty/themes
    if [ ! -f ${config.home.homeDirectory}/.config/ghostty/themes/dankcolors ]; then
      # Create empty placeholder so ghostty doesn't fail to load
      $DRY_RUN_CMD touch ${config.home.homeDirectory}/.config/ghostty/themes/dankcolors
    fi
  '';

  # Create desktop entry for drop-down terminal to use Ghostty's icon
  xdg.dataFile."applications/com.kc.dropterm.desktop".text = ''
    [Desktop Entry]
    Type=Application
    Name=Ghostty Drop-down Terminal
    Comment=Drop-down terminal using Ghostty
    Icon=com.mitchellh.ghostty
    Exec=${pkgs.ghostty}/bin/ghostty --class=com.kc.dropterm
    Terminal=false
    Categories=System;TerminalEmulator;
    StartupWMClass=com.kc.dropterm
    NoDisplay=true
  '';
}
