---
showReleaseNotesUrl: false

requirements:
    requiredStorage:    10
    requiredRam:        3.0
    internetCheckUrl:
        - https://cache.nixos.org/
    check:
        - storage
        - ram
        - power
        - internet
        - screen
    required:
        - storage
        - ram
