---
modules-search: [ local, @out@/lib/calamares/modules ]

instances:
- id:       unfree
  module:   notesqml
  config:   unfree.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - notesqml@unfree
  - partition
  - summary
- exec:
  - partition
  - mount
  - axios
  - users
  - umount
- show:
  - finished

branding: axios
prompt-install: false
dont-chroot: false
