# Hardware configuration (copy from /etc/nixos/hardware-configuration.nix)
# This file should be generated by nixos-generate-config and contain:
# - Boot kernel modules (boot.initrd.availableKernelModules)
# - Kernel modules (boot.kernelModules)
# - Filesystems (fileSystems.*)
# - Swap devices (swapDevices)
# - Hardware-specific settings
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Kernel modules needed in initrd for disk detection
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ]; # or "kvm-intel" for Intel CPUs
  boot.extraModulePackages = [ ];

  # Root filesystem
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
    fsType = "ext4";
  };

  # Boot partition (UEFI)
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/XXXX-XXXX";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # CPU microcode updates
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For Intel: hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # NOTE: Replace UUIDs with your actual disk UUIDs!
  # Find them with: lsblk -f or blkid
  #
  # For easiest setup, just run:
  #   sudo nixos-generate-config
  # And copy /etc/nixos/hardware-configuration.nix to this file
}
