---
modules-search: [ local, @out@/lib/calamares/modules ]

instances:
- id:       unfree
  module:   notesqml
  config:   unfree.conf
- id:       cairnconfig
  module:   notesqml
  config:   cairnconfig.conf

sequence:
- exec:
  - cairndetect
- show:
  - welcome
  - locale
  - keyboard
  - users
  - notesqml@unfree
  - notesqml@cairnconfig
  - partition
  - summary
- exec:
  - partition
  - mount
  - cairn
  - users
  - umount
- show:
  - finished

branding: cairn
prompt-install: false
dont-chroot: false
